### ISSUE TITLE
Make call notes canonical

### ISSUE THREAD

**Issue by lrettig** [stacksgov/resources#15]
Right now, the notes from governance calls 1 and 2 live only in issues (#12, https://github.com/stacksgov/pm/issues/3#issuecomment-593482885). These notes should be cleaned up and moved from the metadata into canonical notes that live inside the repository itself. See, for reference: https://github.com/ethereum/pm/tree/master/All%20Core%20Devs%20Meetings.

- [ ] Meeting 1 (#16)
- [ ] Meeting 2 (https://github.com/stacksgov/pm/issues/3#issuecomment-593482885)
- [x] Meeting 3 (#12)
- [x] Meeting 4 (#19)
- [x] Meeting 5 (#21)

**Comment by whoabuddy** [comment]
I'm for this idea, but recommend an ISO 8601 date on the beginning of each file for better organization!

**Comment by lrettig** [comment]
This was set up in #21 (thanks @whoabuddy!). Remaining task is to move the notes from prior calls into place (see to do list above).

**Comment by whoabuddy** [comment]
Closing in favor of stacksgov/pm#74 and stacksgov/pm#75 that cover the remaining tasks.
