### ISSUE TITLE
Add some resources related to other open source software foundations

### ISSUE THREAD

**Issue by lrettig** [stacksgov/resources#18]
@whoabuddy already started this process in #17. Let's see if we can collect some more information on how other foundations and similar entities are governed. Here are a few that come to mind, feel free to add to this list:

- Apache Foundation (already added)
- Mozilla Foundation
- Linux Foundation
- Python Foundation
- Wikimedia Foundation
- IETF
- W3C

What am I missing?

**Comment by whoabuddy** [comment]
This one came from our last meeting and was not added yet (thanks @joberding!)

- [OpenJS Foundation Goverance](https://openjsf.org/about/governance/)

In my initial searches I didn't find clear governance policies for Mozilla / Linux, but that may have to due with the literal size of their projects. I'm sure it's hidden in there somewhere.

The others sound like good ones to research, I will add here if any others come to mind.

**Comment by whoabuddy** [comment]
Closed [#18](https://github.com/stacksgov/resources/issues/18) via #24
